language: node_js
sudo: false

node_js:
  - "iojs"
  - "8"
  - "7"
  - "6"

branches:
  only:
    - develop
    - master

before_script:
    - yarn install

script:
  - npm run test
  - npm run test:coverage
  - codecov

cache:
  yarn: true
  directories:
    - "node_modules"

after_success:
  - bash <(curl -s https://codecov.io/bash)